= ansible-role-motd
Jonas Pammer <opensource@jonaspammer.at>;
:toc:
:toclevels: 3
:toc-placement!:
:source-highlighter: rouge

ifdef::env-github[]
// https://gist.github.com/dcode/0cfbf2699a1fe9b46ff04c41721dda74#admonitions
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

// Very Relevant Status Badges
https://github.com/JonasPammer/ansible-role-motd/actions/workflows/ci.yml[image:https://github.com/JonasPammer/ansible-role-motd/actions/workflows/ci.yml/badge.svg[Testing CI]]

// Badges about Conventions in this Project
https://conventionalcommits.org[image:https://img.shields.io/badge/Conventional%20Commits-1.0.0-yellow.svg[Conventional Commits]]
https://results.pre-commit.ci/latest/github/JonasPammer/ansible-role-motd/master[image:https://results.pre-commit.ci/badge/github/JonasPammer/ansible-role-motd/master.svg[pre-commit.ci status]]
// image:https://img.shields.io/badge/pre--commit-enabled-brightgreen?logo=pre-commit&logoColor=white[pre-commit, link=https://github.com/pre-commit/pre-commit]
https://open.vscode.dev/JonasPammer/ansible-role-motd[image:https://img.shields.io/static/v1?logo=visualstudiocode&label=&message=Open%20in%20Visual%20Studio%20Code&labelColor=2c2c32&color=007acc&logoColor=007acc[Open in Visual Studio Code]]
image:https://img.shields.io/badge/PRs-welcome-brightgreen.svg?style=flat-square[PRs Welcome]


ifdef::env-github[]
[TIP]
__A single-page version of this README can be found at https://JonasPammer.github.io/ansible-role-motd[
JonasPammer.github.io/ansible-role-motd].__
endif::[]


An Ansible role for configuring static and dynamic login banners on linux machines.

For configuring OpenSSH's Banner, see
https://github.com/JonasPammer/ansible-role-openssh/[ansible-role-openssh].


toc::[]

[[meta]]
== 🔎 Metadata
Below you can find information on…

* the role's required Ansible version
* the role's supported platforms
* the role's https://docs.ansible.com/ansible/latest/user_guide/playbooks_reuse_roles.html#role-dependencies[role dependencies]

.link:meta/main.yml[]
[source,yaml]
----
include::meta/main.yml[]
----


[[requirements]]
== 📌 Requirements
// Any prerequisites that may not be covered by this role or Ansible itself should be mentioned here.
The Ansible User needs to be able to `become`.


The https://galaxy.ansible.com/community/general[`community.general` collection]
must be installed on the Ansible controller.


[[variables]]
== 📜 Role Variables
// A description of the settable variables for this role should go here
// and any variables that can/should be set via parameters to the role.
// Any variables that are read from other roles and/or the global scope (ie. hostvars, group vars, etc.)
// should be mentioned here as well.

[source,yaml]
----
motd_type: [OS-specific for v1, see TODO in setup-update-motd.yml]
----
A MOTD can be implemented in 2 manners:

"`static`"::
Generate a single static `/etc/motd` text file and
dismantle update-motd's scripts so only this file is being shown by `pam_motd`
(traditional motd).

"`update-motd`"::
Activate the `update-motd` functionality
https://www.systutorials.com/docs/linux/man/5-update-motd/[(nicely described in Ubuntu's MAN Page)],
by which the motd is dynamically assembled from a collection of scripts
at login or periodically through the use of a `cron` job.
+
This role will delete the traditional `/etc/motd` file,
leaving only the output of the scripts to be included in the assembled motd.
+
This role will install its own `update-motd` Implementation on systems
without this functionality built into their version of `pam_motd`.
+
Additional Relevant Reading Material on the `update-motd` topic:
+
* https://ownyourbits.com/2017/04/05/customize-your-motd-login-message-in-debian-and-ubuntu/[
Blog Post describing update-motd's history and implementation details]
* https://wiki.ubuntu.com/UpdateMotd[UbuntuWiki's Proposal]

=== Static MOTD Configuration Variables

[source,yaml]
----
motd_static_motd_template: "issue.net"
----
Path to Ansible template ending in `.jinja2`.

[NOTE]
====
This role comes bundled with a pre-defined legal banner.
To use your own templates, ensure your template do not wear the exact names
as the one in link:templates[this roles' `templates` directory].
====

=== Dynamic MOTD Configuration Variables

[source,yaml]
----
motd_dynamic_scripts_system_packages: [OS-specific, see /defaults directory]
----
Packages to be installed by this role using
https://docs.ansible.com/ansible/latest/collections/ansible/builtin/package_module.html[Ansible's package module].

[source,yaml]
----
motd_dynamic_scripts_templates:
  - "00-legal" # in case SSH-Banner didn't show
  - "10-sysinfo"
----
Path to Ansible templates ending in `.jinja2` that are to be generated into `motd_dynamic_scripts_directory`.

[NOTE]
====
This role comes bundled with some already defined templates.
To use your own templates, ensure your templates do not wear the exact names
as the ones in link:templates[this roles' `templates` directory].
====

[source,yaml]
----
motd_dynamic_scripts_directory: [OS-specific by default, see /vars directory]
----
Path to store the templated `motd_dynamic_scripts_templates`.
Must *not* end with `/`.

[source,yaml]
----
motd_dynamic_scripts_backup: false
motd_dynamic_scripts_backup_path: "{{ motd_dynamic_scripts_directory }}-backup"
----
This role ensures that `motd_dynamic_scripts_directory`
*only* contains the files stated in `motd_dynamic_scripts_templates`.

These variables define whether and where to backup files
found in the mentioned directory that are not included in the list
of this role's defined script template names.

[source,yaml]
----
motd_static_motd_backup: false
motd_static_motd_backup_path: "/etc/motd-backup"
----
This role ensure's that only the dynamic scripts
have influence on the resulting motd.

If `/etc/motd` is found to be a normal text file,
these variables define whether and where to backup this file.


[[public_vars]]
== 📜 Facts/Variables defined by this role

Each variable listed in this section
is dynamically defined when executing this role (and can only be overwritten using `ansible.builtin.set_facts`) _and_
is meant to be used not just internally.


[[dependencies]]
== 👫 Dependencies
// A list of other roles should go here,
// plus any details in regard to parameters that may need to be set for other roles,
// or variables that are used from other roles.



[[example_playbooks]]
== 📚 Example Playbook Usages
// Including examples of how to use this role in a playbook for common scenarios is always nice for users.

[NOTE]
====
This role is part of https://github.com/JonasPammer/ansible-roles[
many compatible purpose-specific roles of mine].

The machine needs to be prepared.
In CI, this is done in `molecule/default/prepare.yml`
which sources its soft dependencies from `requirements.yml`:

.link:molecule/default/prepare.yml[]
[source,yaml]
----
include::molecule/default/prepare.yml[]
----

The following diagram is a compilation of the "soft dependencies" of this role
as well as the recursive tree of their soft dependencies.

image:https://raw.githubusercontent.com/JonasPammer/ansible-roles/master/graphs/dependencies_motd.svg[
requirements.yml dependency graph of jonaspammer.motd]
====

.Minimum Viable Play
====
[source,yaml]
----
roles:
    - "jonaspammer.motd"

vars:
    some_var: "some_value"
----
====


[[development]]
== 📝 Development
include::DEVELOPMENT.adoc[]


[[contributing]]
== 💪 Contributing
include::CONTRIBUTING.adoc[]


[[changelog]]
== 🗒 Changelog
Please refer to the
https://github.com/JonasPammer/ansible-role-motd/releases[Release Page of this Repository]
for a human changelog of the corresponding
https://github.com/JonasPammer/ansible-role-bootstrap/tags[Tags (Versions) of this Project].

Note that this Project adheres to Semantic Versioning.
Please report any accidental breaking changes of a minor version update.


[[license]]
== ⚖️ License

.link:LICENSE[]
----
include::LICENSE[]
----
