---
roles:
  - name: jonaspammer.bootstrap
  - name: jonaspammer.core_dependencies
  - name: jonaspammer.shellcheck
# NOTE: list all collections used here (even if included in `ansible`)
collections:
  - name: community.general
