---
# tasks file of ansible-role jonaspammer.motd

- name: Generate static MOTD file and ensure correct owner/group/mode.
  ansible.builtin.template:
    src: "{{ motd_static_motd_template }}.jinja2"
    dest: "/etc/motd"
    owner: root
    group: root
    mode: u=rwx,g=rx,o=rx

- name: stat dynamic motd directory
  ansible.builtin.stat:
    path: "{{ motd_dynamic_scripts_directory }}"
  register: motd__register_stat_dynamic_motd_directory
- block:
    - name: Copy dynamic MOTD files into preservation directory (when exists and preservation configured).
      ansible.builtin.copy:
        remote_src: true
        src: "{{ motd_dynamic_scripts_directory }}"
        dest: "{{ motd_dynamic_scripts_backup_path }}"
        owner: root
        group: root
        mode: u=rwx,g=,o=
    - name: Delete dynamic MOTD script directory.
      ansible.builtin.file:
        path: "{{ motd_dynamic_scripts_directory }}"
        state: absent
  when: motd__register_stat_dynamic_motd_directory.stat.exists
